# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
  - name: LiFiDiamond
    handler: src/EventHandlers.ts
    events:
      - event: BridgeToNonEVMChain(bytes32 indexed transactionId, uint256 indexed destinationChainId, bytes receiver)
      - event: BridgeToNonEVMChainBytes32(bytes32 indexed transactionId, uint256 indexed destinationChainId, bytes32 receiver)
      - event: LiFiGenericSwapCompleted(bytes32 indexed transactionId, string integrator, string referrer, address receiver, address fromAssetId, address toAssetId, uint256 fromAmount, uint256 toAmount)
      - event: LiFiSwappedGeneric(bytes32 indexed transactionId, string integrator, string referrer, address fromAssetId, address toAssetId, uint256 fromAmount, uint256 toAmount)
      - event: LiFiTransferCompleted(bytes32 indexed transactionId, address receivingAssetId, address receiver, uint256 amount, uint256 timestamp)
      - event: LiFiTransferRecovered(bytes32 indexed transactionId, address receivingAssetId, address receiver, uint256 amount, uint256 timestamp)
      - event: LiFiTransferStarted((bytes32,string,string,address,address,address,uint256,uint256,bool,bool) bridgeData)
networks:
  - id: 1 # ethereum
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0xCf914FaFd0e3d2A2a6679ECb4AE0D7893F41994b
  - id: 137 # polygon
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x6e271031ADa1a19C2554f1b758FDE277C8cf5447
  - id: 534352 # scroll
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x1c0C712AC285B598709c47F4e6FD7197F9322247
  - id: 100 # gnosis
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x6e271031ADa1a19C2554f1b758FDE277C8cf5447
  - id: 43114 # avalanche
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x6e271031ADa1a19C2554f1b758FDE277C8cf5447
  - id: 42161 # arbitrum
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x6e271031ADa1a19C2554f1b758FDE277C8cf5447
  - id: 56 # bsc
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x6e271031ADa1a19C2554f1b758FDE277C8cf5447
  - id: 42220 # celo
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x1c0C712AC285B598709c47F4e6FD7197F9322247
  - id: 10 # optimism
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x47446051f4FC964274a26811526Fb8a6cc456D33
  - id: 8453 # base
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x1b567cFdAFbD5318095DF679A7a9C68bFd51A410
  - id: 5000 # mantle
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x1c0C712AC285B598709c47F4e6FD7197F9322247
  - id: 480 # worldchain
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x645Bf3d1A83f703726091bF4baf3fD84A104C4F8
  - id: 1135 # lisk
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x645Bf3d1A83f703726091bF4baf3fD84A104C4F8
  - id: 146 # sonic
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE
          - 0x7E1DDe93e73B7177e95a9eCd9268356560F46dc2
  # - id: 80084 # berachain
  #   start_block: 0
  #   contracts:
  #     - name: LiFiDiamond
  #       address:
  #         - 0xf909c4Ae16622898b885B89d7F839E0244851c66
  #         - 0x6852Dca9eb64f64e556d725Da7CCC2C371239728
  - id: 1868 # soneium
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x864b314D4C5a0399368609581d3E8933a63b9232
          - 0x38b2e9F11D9d8E8f0aA4e4cbDb695706534D3351
  - id: 130 # unichain
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x864b314D4C5a0399368609581d3E8933a63b9232
          - 0x38b2e9F11D9d8E8f0aA4e4cbDb695706534D3351
  - id: 999 # hyperevm
    start_block: 0
    contracts:
      - name: LiFiDiamond
        address:
          - 0x0a0758d937d1059c356D4714e57F5df0239bce1A
          - 0x97306A75E022e892eEe184440678d34c831dd1CD
# - id: 1088 # katana
#   start_block: 0
#   contracts:
#   - name: LiFiDiamond
#     address:
#     - 0xC59fe32C9549e3E8B5dCcdAbC45BD287Bd5bA2bc
#     - 0x5faB4C8B01325d85424D31C167B2c9829F92Ba8f
# - id: 98864 # plume
#   start_block: 0
#   contracts:
#   - name: LiFiDiamond
#     address:
#     - 0x6f5C8Bb0C5Fe4ECeAC40EE1C238EaB6bbb29761c
#     - 0x6EC18Cc9A67c37A792a5BdA8530A7824e6ab80e9
unordered_multichain_mode: true
preload_handlers: true
